overrides:
  ceph:
    conf:
      global:
        lockdep: true
    log-ignorelist:
      - missing required features
      - \(MDS_CACHE_OVERSIZED\)
      - \(MDS_TRIM\)
tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_admin
        - tasks.cephfs.admin.test_fs_swap
